run-name: Deploy dukongo.kg by @${{ github.actor }}

on:
  push:
    branches: ["*"]
    
jobs:
  front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
            key: ${{ secrets.PRIVATE_KEY }}
            known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -H dukongo.kg >> ~/.ssh/known_hosts

      - name: Make fake package-lock for install node
        run: touch package-lock.json

      - name: Install nodejs 21.6.1
        uses: actions/setup-node@v3
        with:
          node-version: 21.6.1
          cache: "npm"

      - name: Build
        run: npm ci && npm run build

      - name: Copy code to remote
        run: rsync -a --delete ./.output/ root@dukongo.kg:/app/www/nuxt    
      
      
      - name: Restart container
        run: ssh root@$dukongo.kg "cd /app/infrastructure && docker compose down && docker compose up -d"